[Feature] comment,review 좋아요
ochoWhat2do/what2do pull request #15
Opened 2023-08-25 07:44 UTC by SH-Lee2023

## 관련 Issue

comment, review like

#11

## 변경 사항

* comment 좋아요/좋아요 취소 기능
* review 좋아요/좋아요 취소 기능

## Todo List

  

* 기입 예: 예외 처리를 추가적으로 해줘야 합니다.
* 기입 예: 아직 포스트맨 테스트를 해보지 않았습니다.

## Check List

 

- [ ] 포스트맨으로 체크해 보았나요?
- [ ] 테스트 코드를 작성하셨나요?

- [ ] 다른 팀원의 PR을 보고 코드 리뷰를 남겨 보았나요?
- [x] 별도의 이슈를 생성해서 해결하겠습니다.
- [X] 다른 팀원에게 문의 했는지 체크해봅니다.

## 트러블 슈팅

2023-08-25 08:29 UTC, sxi8022 requested changes
리뷰하겠습니다 postman으로 테스트 하셨다면 checklist에 x표시 해주시면됩니다.

2023-08-25 08:29 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/entity/ReviewLike.java
> +  public User getUsr() { return user; }
getUsr -> getUser 로 맞추는게 좋을 것 같습니다.

2023-08-25 08:29 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
review.removeLike 이부분만 해도 좋아요 제거가 되나요 ? 
 포스트맨으로 테스트 해보시고 알려주세요

2023-08-25 08:29 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/comment/service/CommentServiceImpl.java
> +        CommentLike likeToRemove = commentLikeRepository.findByUserAndComment(user, comment)
likeToRemove 이부분 중복되는 변수가 없다면 commentLike 라고 변수명을 써도 괜찮을것 같아요

2023-08-25 08:29 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
>          ReviewLike newLike = new ReviewLike(user, review);
이부분도 중복이없다면 reviewLike 이렇게 변수명을 설정해도 좋을 것 같습니다.

2023-08-28 05:18 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/entity/ReviewLike.java
> +  public User getUsr() { return user; }
수정했습니다.

2023-08-28 05:18 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/comment/service/CommentServiceImpl.java
> +        CommentLike likeToRemove = commentLikeRepository.findByUserAndComment(user, comment)
수정했습니다.

2023-08-28 05:19 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
>          ReviewLike newLike = new ReviewLike(user, review);
수정했습니다.

2023-08-28 08:32 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
포스트맨 테스트 완료

2023-08-28 08:51 UTC, sxi8022 approved these changes
테스트 완료

2023-08-28 09:03 UTC, merged