feature/5/게시글(리뷰) 개발
ochoWhat2do/what2do pull request #7
Opened 2023-08-22 01:04 UTC by SH-Lee2023

## 관련 Issue

게시글(리뷰) 개발

* #5

## 변경 사항

* 리뷰 작성, 조회, 수정, 삭제 기능 구현
* 리뷰 좋아요/ 좋아요 취소 기능 구현

## Todo List

* 댓글 기능 구현 중
* 아직 포스트맨 테스트를 해보지 않았습니다.

## Check List

 

- [X] 포스트맨으로 체크해 보았나요?
- [X] 테스트 코드를 작성하셨나요?

2023-08-22 01:53 UTC, sxi8022 requested changes
리뷰입니다.

2023-08-22 01:53 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewService.java
> +
리뷰 시작하겠습니다.

2023-08-22 01:53 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewService.java
> +@Service
10번째 줄에 @Service는 인터페이스 이므로 지워도 될 것 같습니다.

2023-08-22 01:53 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/dto/ReviewDetailDto.java
> +    private List<CommentResponseDto> comments; // 댓글 목록 등
// 댓글 목록 등 
이부분 지워도 될 것 같습니다.

2023-08-22 01:53 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/controller/ReviewController.java
> +            return ResponseEntity.notFound().build();
null 체크를 할 필요는 없어 보여요 
서비스에서 데이터가 있는지 없는지 체크하고 없으면 custom 에러코드를 출력하잖아요?
그 부분에서 다 처리하도록 두면 될 것 같고 
컨트롤러에서는 간략하게 
@Operation(summary = "보드 수정", description = "배경 색상 / 보드 이름 / 설명을 수정합니다.")
    @PutMapping("/boards/{boardId}")
    public ResponseEntity<BoardResponseDto> updateBoards(@PathVariable("boardId") Long id, @Valid @RequestBody BoardRequestDto requestDto, @AuthenticationPrincipal UserDetailsImpl userDetails) {
        BoardResponseDto responseDto = boardService.updateBoard(id, requestDto, userDetails.getUser());
        return ResponseEntity.ok().body(responseDto);
    }

이런식으로 코드 작성을 하면 좋을 것 같습니다!

2023-08-22 01:53 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewService.java
> +    List<ReviewResponseDto> getAllReviews();
전체리뷰는 페이징 처리를 알아보는 것이 좋을 것 같습니다. 
만약 단시간내에 하기 어렵다면 별도의 이슈를 생성하여 페이징 처리를 일괄적으로 전체조회 하는 부분에 적용해보죠

2023-08-22 06:14 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/service/ReviewService.java
> +@Service
@service 삭제완료

2023-08-22 06:14 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/dto/ReviewDetailDto.java
> +    private List<CommentResponseDto> comments; // 댓글 목록 등
삭제 완료

2023-08-22 06:15 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/controller/ReviewController.java
> +            return ResponseEntity.notFound().build();
null 체크부분 수정 완료

2023-08-22 06:15 UTC, SH-Lee2023 commented on src/main/java/com/ocho/what2do/review/service/ReviewService.java
> +    List<ReviewResponseDto> getAllReviews();
전체리뷰 페이징 처리 추가

2023-08-22 06:26 UTC, sxi8022 reviewed
페이징하고 변수수정이 필요해 보입니다.

2023-08-22 06:26 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/controller/ReviewController.java
> +            @PathVariable("review_Id") Long review_Id,
Long review_Id 이부분 Long reviewId 이런식으로 카멜케이스형식을 주면 될 것 같아요

2023-08-22 06:26 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/controller/ReviewController.java
> +        return ResponseEntity.ok(reviewPage);
spring 강의에 나온 예제를 참고해서 
@GetMapping("/postlist")
    @ResponseBody
    public ResponseEntity list(
            @RequestParam("page") int page,
            @RequestParam("size") int size,
            @RequestParam("sortBy") String sortBy,
            @RequestParam("isAsc") boolean isAsc,
            @RequestParam(value="postName", required = false) String postName,
            @AuthenticationPrincipal UserDetailsImpl userDetails
    ) {
        Page<PostResponseDto> postDtoList;
        if (postName != null && !postName.isEmpty()) {
            postDtoList = postService.getPostListByPostName(page-1, size, sortBy, isAsc, postName);

        } else {
            postDtoList = postService.getPostList(userDetails,
                page-1, size, sortBy, isAsc);
        }
        return new ResponseEntity<>(postDtoList, HttpStatus.OK);
    }
    이런형식으로 페이징을 주면 좋을 것 같습니다.  postName(검색할 게시글명)은 없어도 되고 
    sortBy, isAsc 변수는 필요할 것 같아요.

2023-08-22 08:27 UTC, sxi8022 reviewed
추가 수정사항이 생겼습니다.

2023-08-22 08:27 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/entity/Review.java
> -  @Column
@Column(name="order_no")
  private Long orderNo;
 이렇게 수정하고 테이블 다삭제하고 다시 만드시면 에러 안날 겁니다. 
 mysql에서 order을 예약어로 활용한다고하더라고요.

2023-08-24 06:55 UTC, sxi8022 reviewed
comment 에 대한 리뷰입니다.

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/comment/dto/CommentCreateRequestDto.java
> +    private Long review_Id;
자바 클래스 내에서는 
카멜케이스 형식 유지해주세요 
review_Id -> reviewId

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/controller/ReviewController.java
> +    @GetMapping("/reviews/{review_Id}") // /api/stores/{store_id}/reviews
머지 되면 /api/stores/{store_id}/reviews 이 형식으로 url 수정해주세요 테스트도 하면서

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/entity/ReviewLike.java
> +  public User getUse() {
getUse -> getUser 이름이 잘못 된 것 같습니다. 연관된 메소드도 수정하면 될 것 같습니다.

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
> +        reviewRepository.save(review);
좋아요만 취소하는데 왜 
  reviewRepository.save(review); 이부분이 들어가는 건가요? 
  써야한다면 이유를 말씀해주시면 좋을 것 같아요

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/service/ReviewServiceImpl.java
> +        reviewRepository.save(review);
좋아요만 취소하는데 왜
 reviewRepository.save(review);이부분이 들어가는 건가요?
써야한다면 이유를 말씀해주시면 좋을 것 같아요
아니면 테스트해보시고 이상없으면 지워주세요

2023-08-24 06:55 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/comment/service/CommentServiceImpl.java
> +    @Transactional
select 하는 메소드이므로
@Transactional(readonly=true) 속성을 주는 것 이 좋을 것 같습니다.

2023-08-24 07:22 UTC, sxi8022 reviewed
리뷰완료2

2023-08-24 07:22 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/comment/service/CommentServiceImpl.java
> +        commentRepository.save(comment);
좋아요만 취소하면 될 것 같아요
commentRepository.save(comment); 이부분은 제거 하고 테스트해보시고 필요없다면 지우시는게 좋을 것 같습니다.

2023-08-24 07:22 UTC, sxi8022 commented on src/main/java/com/ocho/what2do/review/dto/ReviewResponseDto.java
> +
private int likeCount;  // 좋아요 수 
선언하시고 (댓글 도 마찬가지) 
좋아요 수는 예시와 같이 size를 대입하면 될 것 같아요 
return PostResponseDto.builder()
        .id(post.getId())
        .title(post.getTitle())
        .content(post.getContent())
        .updateDate(post.getUpdateDate())
        .createDate(post.getCreateDate())
        .likeCount(post.getPostLikes().size())
        .build();

2023-08-25 00:58 UTC, sxi8022 approved these changes
일부 건은 추후 처리(좋아요)

2023-08-25 00:59 UTC, merged